<?PHP
include("../../bd/informe_semanal_DB.php");
$respuesta=guardar($_POST);
$contador_1=0;
while($contador_1<sizeof($_POST["array_checkbox_area_formulario_semanal"])){
    $area=$_POST["array_checkbox_area_formulario_semanal"][$contador_1];
    guardar_area($area,$_POST,$respuesta["id"]);
    $contador_1++;
}
$contador_2=0;
while($contador_2<sizeof($_POST["array_checkbox_serie_formulario_semanal"])){
    $serie=$_POST["array_checkbox_serie_formulario_semanal"][$contador_2];
    guardar_serie($serie,$_POST,$respuesta["id"]);
    $contador_2++;
}
$respuesta_servidor=["respuesta_servidor"=>$respuesta["respuesta"]];
print(json_encode($respuesta_servidor));

?>